path_to_data: "data/processed/not_transformed/"
path_to_model: "online_inference/models/linear_model_on_not_transformed.joblib"
iterations: 10000
C: 1
report_file: "reports/linear_model_on_not_transformed_report.txt"